name: CI/CD Pipeline

on:
  push:
    branches: [ roo ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8, 3.9, '3.10']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest pytest-cov
    
    - name: Install package
      run: |
        pip install -e .
    - name: Run tests (cross-platform)
      run: |
        python run_tests.py --all --no-gui
        
    - name: Run installation tests
      run: |
        python tests/run_installation_test.py
        
    - name: Test dependency management
      run: |
        python tests/test_dependency_management_integration.py
      
      
  merge-to-main:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/roo' && success()
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create main branch if it doesn't exist
      run: |
        if ! git ls-remote --heads origin main | grep main; then
          git checkout -b main
          git push -u origin main
        fi
    
    - name: Merge roo into main
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git checkout main
        git pull origin main
        git merge origin/roo --no-ff -m "Merge roo branch via GitHub Actions [CI]"
        git push origin main